version: '3.8'

services:
  backend:
    build: ./back
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=pass123 
      - DB_NAME=adsum
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: adsum

  frontend:
    build: ./front
    ports:
      - "80:80"
    depends_on:
      - backend
